name: 'CI build'
trigger:
  branches:
    include:
    - master
    - feature/*
  paths:
    exclude:
    - README.md

jobs:
- job: default
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      DefaultGCC:
         IMAGE: 'foonathan/micro_cpp_gcc'
      DefaultClang:
         IMAGE: 'foonathan/micro_cpp_clang'
  steps:
    - script: docker run -v "$PWD:/root/lex" $(IMAGE) bash -c "cmake lex/ && cmake --build . && ctest --output-on-failure"
      displayName: "Compiling using $(IMAGE)"
